import type {
  PokemonImageRef,
  PokemonTypeRef,
  PokemonAbilityRef,
  PokemonMoveRef,
  PokemonAspectRef,
  PokemonFormType,
  PokemonAbilitySlotRef,
  PokemonFormAbility,
  PokemonMoveLearnMethodRef,
  PokemonFormMove,
  PokemonLabel,
  PokemonItemRef,
  PokemonDropPercentage,
  PokemonDropRange,
  PokemonFormDrops,
  PokemonFormHitbox,
  PokemonFormAspectCombo,
  PokemonAspectChoiceRef,
  PokemonBehaviour,
  PokemonSpeciesLighting,
  PokemonSpeciesRiding,
  PokemonFormOverrides,
  PokemonForm,
  PokemonExperienceGroup,
  PokemonEggGroup,
  PokemonSpeciesWithForms,
  PokemonSpawnConditionWeather,
  PokemonSpawnConditionSky,
  PokemonSpawnConditionPosition,
  PokemonSpawnConditionLure,
  PokemonSpawnCondition,
  PokemonSpawn,
} from '@aglaea/contract';

export type {
  PokemonImageRef as ImageRef,
  PokemonTypeRef as TypeRef,
  PokemonAbilityRef as AbilityRef,
  PokemonMoveRef as MoveRef,
  PokemonAspectRef as AspectRef,
  PokemonLabel as LabelRef,
  PokemonEggGroup as EggGroupRef,
  PokemonFormType as FormType,
  PokemonAbilitySlotRef as AbilitySlot,
  PokemonFormAbility as FormAbility,
  PokemonMoveLearnMethodRef as MoveMethod,
  PokemonFormMove as FormMove,
  PokemonFormHitbox as Hitbox,
  PokemonSpeciesLighting as Lighting,
  PokemonSpeciesRiding as Riding,
  PokemonBehaviour as Behaviour,
  PokemonAspectChoiceRef as AspectChoice,
  PokemonFormAspectCombo as AspectCombo,
  PokemonItemRef as ItemRef,
  PokemonDropPercentage as DropPercentage,
  PokemonDropRange as DropRange,
  PokemonFormDrops as Drops,
  PokemonSpawnConditionWeather as SpawnWeather,
  PokemonSpawnConditionSky as SpawnSky,
  PokemonSpawnConditionPosition as SpawnPosition,
  PokemonSpawnConditionLure as SpawnLure,
  PokemonSpawnCondition as SpawnCondition,
  PokemonSpawn as Spawn,
  PokemonFormOverrides as FormOverrides,
  PokemonForm as Form,
  PokemonExperienceGroup as ExperienceGroup,
  PokemonSpeciesWithForms as Pokemon,
};
